name: dry-transaction
codacy_id: f2c8f3f2e96a477faee00109cfb2090d
gemspec:
  authors: ["Tim Riley"]
  email: ["tim@icelab.com.au"]
  summary: "Business Transaction Flow DSL"
  runtime_dependencies:
    - [dry-core, "~> 1.0"]
    - [dry-events, "~> 1.0"]
    - [dry-matcher, "~> 1.0"]
    - [dry-monads, "~> 1.6"]
